# Week 8 NumPy and Pandas Intro

## 1. Numpy (Numerical Python)

- 과학적, 수학적 데이터를 정리/처리 하기 위한 라이브러리
- NumPy의 array class 를 ndarray 로 명명한다
- 대규모 행렬 데이터를 효율적으로 처리하도록 설계 되어 있다.<br>
    **<행렬이라 함은, 하나의 변수 안에 여러 값을 저장하고자 할 때 사용하는 것>**
- NumPy는 생성할 때 크기가 고정 된다.<br>
    **<하나의 행렬을 생성하고 이후 그 크기를 수정하면 기존의 행렬이 삭제 되고 새로운 행렬이 생성된다.>**
- 리스트와 다르게 유연하지 못하다. 하나의 열에 같은 종류의 데이터만 입력이 가능하다.
- 하지만 리스트와 비교하여 메모리를 덜 소모하고 계산과정에서 보다 적은 단계를 거친다.

## 2. Array 생성

### 1) Array dimension

In [3]:
import numpy as np #이 과정을 안 해주면 밑에 다 에러 뜸.

In [4]:
arr1d= np.array([1,2,3]) #1dimension
arr1d

array([1, 2, 3])

In [5]:
arr2d= np.array([(1,2,3),(4,5,6),(7,8,9)]) #2dimension
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
arr3d=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]],[[13,14,15],[16,17,18]]]) #3dimension
print(arr3d)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]


<img src="http://www.oreilly.com/library/view/elegant-scipy/9781491922927/assets/elsp_0105.png">

### 2) numpy.arange

pythoon의 built-in functioin 중 range()와 같으나, 리스트 대신 ndarray를 반환.<br>
half-open interval로 변수 생성(마지막 값 생략)

In [10]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.zeros(10) #0만 10개 있는 행렬

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [13]:
np.zeros((2,5)) #0만으로 2*5 행렬을 만든다

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [14]:
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

배열의 크기가 커지면 배열을 초기화하는데도 시간이 걸린다. 이 시간을 단축하려면 배열을 생성만 하고 특정한 값으로 초기화를 하지 않는 empty 명령을 사용한다. empty 명령으로 생선된 배열에는 기존 메모리에 저장되어 있던 값이 있으므로 배열의 원소 값을 미리 알 수 없다. <br><i>#무슨 말인 지 잘 모르겠어요...<i>

In [15]:
np.empty(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

### 3) numpy.reshape

행렬의 값을 바꾸지 않으면서 모양만 변환하고자 할 때

In [16]:
np.zeros(10).reshape(2,5)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [17]:
np.zeros(4)

array([0., 0., 0., 0.])

### 4) ndarray 속성들

In [19]:
# "ndim" 배열의 dimension의 수를 출력
print(arr1d.ndim)

1


In [20]:
#"itemsize" 배열의 byte수를 출력
arr2d.itemsize

4

In [22]:
# "dtype" 배열의 data type를 출력
arr2d.dtype

dtype('int32')

In [23]:
#"size" 배열의 원소 개수를 출력
arr2d.size

9

In [25]:
#"shape"배열의 shape를 (행,열)로 출력
arr3d.shape

(3, 2, 3)

### 5) NumPy 배열 연산

In [28]:
a2d=np.array([(1,2,3),(4,5,6),(7,8,9)])
a2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [29]:
a2d+1

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [30]:
a2d*a2d

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [31]:
a2d1=a2d+1
a2d1<a2d

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

In [32]:
a2d1>a2d

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

### 6) NumPy 배열 인덱싱, 슬라이싱

In [34]:
index=np.arange(0,20,2)
print(index)

[ 0  2  4  6  8 10 12 14 16 18]


In [35]:
index[5]

10

Basic slice syntax is "i:j:k"<br><br>
i=Starting index<br>
j=Stoping index<br>
k=Step<br>

In [36]:
index[0:10:3]

array([ 0,  6, 12, 18])

In [37]:
index[5:9]

array([10, 12, 14, 16])

In [39]:
index[5:9]=100
index

array([  0,   2,   4,   6,   8, 100, 100, 100, 100,  18])

In [40]:
index[:]=100
index

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

<i>더 고차원의 배열을 인덱싱을 하면 원소 값이 출력 되는 것이 아니라, 하나의 배열(행)을 인덱싱 한다.<i>

In [42]:
a2d=np.array([(1,2,3),(4,5,6),(7,8,9)])
print(a2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [43]:
a2d[0] #0번째 행이 출력

array([1, 2, 3])

In [44]:
a2d[0,0] #왼쪽 부터 0번째 원소가 출력

1

In [45]:
a2d[1]=10,11,12
a2d

array([[ 1,  2,  3],
       [10, 11, 12],
       [ 7,  8,  9]])

<img src = "https://www.oreilly.com/library/view/python-for-data/9781449323592/httpatomoreillycomsourceoreillyimages2172114.png" width = 300>

In [46]:
a2d[:2,1:]

array([[ 2,  3],
       [11, 12]])

In [47]:
a3d=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

In [48]:
a3d[1]

array([[ 7,  8,  9],
       [10, 11, 12]])

In [49]:
a3d[1,1]=13
a3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [13, 13, 13]]])

# Pandas

파이썬의 가장 큰 약점으로 여겨져온 데이터 분석 및 모델링 부문을 보완해주는 것이 Pandas! 굳이 R을 사용하지 않더라도 파이썬만으로 데이터 분석 가능하게 함.

- Convert a Python list, dict, or NumPy arrray into a Pandas data frame
- Open a local file using Pandas (e.g. CSV, EXCEL, TXT files, and etc.) 
- Open a remote file or database through a URL

**Pandas의 가장 기본적인 데이터 구성**

1) Series <br>
- 1차원 배열과 비슷하나, NumPy와는 다르게 안에 속하는 데이터 값이 다른 종류여도 괜찮다.

2) DataFrame<br>
- 데이터 표. 데이터를 행과 열로 정리하여 2차원의 배열 형태로 정렬한 것.<br>

In [50]:
import pandas as pd

## 1. Series

In [52]:
b_w = pd.Series([12,13,14,'number'])
b_w

0        12
1        13
2        14
3    number
dtype: object

In [54]:
bw2=pd.Series([1,2,3,4], index=['a','b','c','d'])
bw2

a    1
b    2
c    3
d    4
dtype: int64

In [55]:
bw2['a']

1

In [56]:
bw2[bw2>2]

c    3
d    4
dtype: int64

In [57]:
bw2*2

a    2
b    4
c    6
d    8
dtype: int64

## 2. 데이터 로드

요약:<br>
- pd.read_csv
- pandas 만의 DataFrame=table
- 0으로 시작하는 특수한 인덱스
- 각 변수의 데이터 타입 확인 가능

In [61]:
df=pd.read_csv('./rain.csv')
df

month_2014  rainfall_inches
0         jan              5.3
1         feb              5.4
2         mar              4.8
3         apr              4.7
4         may              3.3
5         jun              1.2
6         jul              0.8
7         aug              0.7
8         sep              NaN
9         oct              3.9
10        nov              4.5
11        dec              5.9

- 엑셀로 만든 csv파일을 Pandas가 읽어 DataFrame을 NumPy의 표 형식으로 재구성한다.
- 자동으로 0부터 시작하는 유니크한 index로 DataFrame을 구성
- 자동으로 csv파일의 데이터 값의 종류를 추론
- Numpy와는 다르게 한 테이블에 여러 종류의 데이터 종류를 입력할 수 있지만, 한 열 내에서는 같은 종류의 데이터 값을 입력해야 한다.

### 1) Dataframe

In [62]:
df.shape #dataframe의 행과 열의 수를 확인

(12, 2)

In [63]:
df.columns #열의 인덱스 확인

Index(['month_2014', 'rainfall_inches'], dtype='object')

In [64]:
df.dtypes #각 인덱스의 데이터 타입

month_2014          object
rainfall_inches    float64
dtype: object

**인덱싱으로 dataframe의 행을 선택할 수 있으며, 열은 열의 이름을 부름으로써 선택 가능하다.**

In [65]:
df['rainfall_inches'][:6]

0    5.3
1    5.4
2    4.8
3    4.7
4    3.3
5    1.2
Name: rainfall_inches, dtype: float64

**Rainfall_inches 열에 관련된 기초 통계치를 하나의 명령으로 쉽게 구할 수 있다.**

In [66]:
df['rainfall_inches'].describe()

count    11.000000
mean      3.681818
std       1.923444
min       0.700000
25%       2.250000
50%       4.500000
75%       5.050000
max       5.900000
Name: rainfall_inches, dtype: float64

<i>Pandas는 9월에 있는 빈 데이터 값 역시 고려하여 올바른 통계치를 자동으로 구해준다.</i>

In [67]:
df['rainfall_inches'].max()

5.9

In [68]:
df['rainfall_inches'].min()

0.7

In [69]:
df['rainfall_inches'].median()

4.5

보다시피, 필요한 통계 정보를 하나 하나 따로 구할 수도 있다! >_<

### 3) 인덱싱 & 슬라이싱

Dataframe에서 인덱싱을 하는 방법은 두 가지이다.
- loc: 인덱스에 있는 값을 기반으로 데이터를 추출하며, 마지막 값 역시 포함한다. (label 기반 추출)
- iloc: 인덱스 위치를 기반으로 데이터를 추출하고, 여느 인덱싱 처럼 마지막 값을 포함하여 출력하지 않는다.(Integer position 기반 추출)

In [70]:
df.loc[0:6,:'rainfall_inches'] #rainfall_inches 열의 7번째 행까지 추출하라는 의미

month_2014  rainfall_inches
0        jan              5.3
1        feb              5.4
2        mar              4.8
3        apr              4.7
4        may              3.3
5        jun              1.2
6        jul              0.8

In [73]:
df.iloc[0:6,0:2] #6번째 행, 1번째부터 3번째 열까지 호출

month_2014  rainfall_inches
0        jan              5.3
1        feb              5.4
2        mar              4.8
3        apr              4.7
4        may              3.3
5        jun              1.2

**dataframe의 인덱스(0,1,2,3,4,5... 또는 'month_2014','rainfall_inches'가 0번째 항목이 아님을 잘 보아라!)**

### 3) 값 필터링

특정 조건에 따라 df안의 값들을 추출 할 수 있다.

In [75]:
df['rainfall_inches']<4

0     False
1     False
2     False
3     False
4      True
5      True
6      True
7      True
8     False
9      True
10    False
11    False
Name: rainfall_inches, dtype: bool

nested 형식으로 코드를 입력하지 않아 bool형식으로 출력 된 것.

In [76]:
df[df['rainfall_inches']<6] #특정 행 안에서 n보다 작은 값을 호출

month_2014  rainfall_inches
0         jan              5.3
1         feb              5.4
2         mar              4.8
3         apr              4.7
4         may              3.3
5         jun              1.2
6         jul              0.8
7         aug              0.7
9         oct              3.9
10        nov              4.5
11        dec              5.9

짜잔~ 표 형식으로 나온다!

**하나 이상의 열 값들을(상이한 열을 참조하는 하나 이상의 조건) 기반으로 행을 추출할 수도 있다.**

In [77]:
df[(df['month_2014']=='jan')&(df['rainfall_inches']>5)] #2개 이상의 조건을 만족시키는 값 호출

month_2014  rainfall_inches
0        jan              5.3

### 4) 문자열 함수를 이용하여 필터링

In [78]:
df[df['month_2014'].str.contains('j')]

month_2014  rainfall_inches
0        jan              5.3
5        jun              1.2
6        jul              0.8

In [79]:
df[df['month_2014'].str.contains('j')]['rainfall_inches'].quantile(.5)

1.2

### 5) 결측치 (Missing data)

In [80]:
df[df['rainfall_inches'].notnull()]
#위에서 원자료와 비교해보면 8번째 인덱스 값이 결측치여서 제외됨!!

month_2014  rainfall_inches
0         jan              5.3
1         feb              5.4
2         mar              4.8
3         apr              4.7
4         may              3.3
5         jun              1.2
6         jul              0.8
7         aug              0.7
9         oct              3.9
10        nov              4.5
11        dec              5.9

### 6) 정렬

In [81]:
df.sort_values(['rainfall_inches'],ascending=False)

month_2014  rainfall_inches
11        dec              5.9
1         feb              5.4
0         jan              5.3
2         mar              4.8
3         apr              4.7
10        nov              4.5
9         oct              3.9
4         may              3.3
5         jun              1.2
6         jul              0.8
7         aug              0.7
8         sep              NaN

In [82]:
df.sort_values(['rainfall_inches'],ascending=True)

month_2014  rainfall_inches
7         aug              0.7
6         jul              0.8
5         jun              1.2
4         may              3.3
9         oct              3.9
10        nov              4.5
3         apr              4.7
2         mar              4.8
0         jan              5.3
1         feb              5.4
11        dec              5.9
8         sep              NaN

### 6) Unique value 목록 만들기 & 갯수 세기

In [83]:
print(df['month_2014'].unique()) #month_2014열의 항목 값을 목록화

['jan' 'feb' 'mar' 'apr' 'may' 'jun' 'jul' 'aug' 'sep' 'oct' 'nov' 'dec']


In [84]:
df['month_2014'].count() #개수

12